# Generated by Django 4.1.5 on 2023-01-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('image', models.ImageField(upload_to='Site/static/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контент: главная страница',
                'verbose_name_plural': 'Контент: главная страница',
            },
        ),
        migrations.CreateModel(
            name='RelevancePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalaryByYears_Graph', models.ImageField(upload_to='Site/static/images/', verbose_name='График: Динамика уровня зарплат по годам')),
                ('SalaryByYears_16', models.IntegerField(verbose_name='16 year')),
                ('SalaryByYears_17', models.IntegerField(verbose_name='17 year')),
                ('SalaryByYears_18', models.IntegerField(verbose_name='18 year')),
                ('SalaryByYears_19', models.IntegerField(verbose_name='19 year')),
                ('SalaryByYears_20', models.IntegerField(verbose_name='20 year')),
                ('SalaryByYears_21', models.IntegerField(verbose_name='21 year')),
                ('SalaryByYears_22', models.IntegerField(verbose_name='22 year')),
                ('SalaryByYears_23', models.IntegerField(verbose_name='23 year')),
                ('CountByYears_Graph', models.ImageField(upload_to='Site/static/images/', verbose_name='График: Динамика количества вакансий по годам')),
                ('CountByYears_16', models.IntegerField(verbose_name='16 year')),
                ('CountByYears_17', models.IntegerField(verbose_name='17 year')),
                ('CountByYears_18', models.IntegerField(verbose_name='18 year')),
                ('CountByYears_19', models.IntegerField(verbose_name='19 year')),
                ('CountByYears_20', models.IntegerField(verbose_name='20 year')),
                ('CountByYears_21', models.IntegerField(verbose_name='21 year')),
                ('CountByYears_22', models.IntegerField(verbose_name='22 year')),
                ('CountByYears_23', models.IntegerField(verbose_name='23 year')),
            ],
            options={
                'verbose_name': 'Контент: востребованность',
                'verbose_name_plural': 'Контент: востребованность',
            },
        ),
    ]
