# Generated by Django 4.1.5 on 2023-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevancepageinfo',
            name='CountByYears_Graph',
            field=models.ImageField(upload_to='app/static/images/', verbose_name='График: Динамика количества вакансий по годам'),
        ),
        migrations.AlterField(
            model_name='relevancepageinfo',
            name='SalaryByYears_Graph',
            field=models.ImageField(upload_to='app/static/images/', verbose_name='График: Динамика уровня зарплат по годам'),
        ),
    ]
