# Generated by Django 4.1.5 on 2023-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_relevancepageinfo_countbyyears_graph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinfo',
            name='image',
            field=models.ImageField(upload_to='app/static/images/', verbose_name='Изображение'),
        ),
    ]
