# Generated by Django 4.1.5 on 2023-01-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_homepageinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=30, verbose_name='Город 1')),
                ('city2', models.CharField(max_length=30, verbose_name='Город 2')),
                ('city3', models.CharField(max_length=30, verbose_name='Город 3')),
                ('city4', models.CharField(max_length=30, verbose_name='Город 4')),
                ('city5', models.CharField(max_length=30, verbose_name='Город 5')),
                ('SalaryGraph', models.ImageField(upload_to='app/static/images/', verbose_name='График: Уровень зарплат по городам')),
                ('Salary1', models.IntegerField(verbose_name='Уровень зарплат 1')),
                ('Salary2', models.IntegerField(verbose_name='Уровень зарплат 2')),
                ('Salary3', models.IntegerField(verbose_name='Уровень зарплат 3')),
                ('Salary4', models.IntegerField(verbose_name='Уровень зарплат 4')),
                ('Salary5', models.IntegerField(verbose_name='Уровень зарплат 5')),
                ('CountGraph', models.ImageField(upload_to='app/static/images/', verbose_name='График: Доля вакансий по городам')),
                ('Count1', models.IntegerField(verbose_name='Уровень зарплат 1')),
                ('Count2', models.IntegerField(verbose_name='Уровень зарплат 2')),
                ('Count3', models.IntegerField(verbose_name='Уровень зарплат 3')),
                ('Count4', models.IntegerField(verbose_name='Уровень зарплат 4')),
                ('Count5', models.IntegerField(verbose_name='Уровень зарплат 5')),
            ],
            options={
                'verbose_name': 'Контент: География',
                'verbose_name_plural': 'Контент: География',
            },
        ),
    ]
