# Generated by Django 4.1.5 on 2023-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_geographypageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill16', models.TextField(verbose_name='Навык 16 year')),
                ('Skill17', models.TextField(verbose_name='Навык 17 year')),
                ('Skill18', models.TextField(verbose_name='Навык 18 year')),
                ('Skill19', models.TextField(verbose_name='Навык 19 year')),
                ('Skill20', models.TextField(verbose_name='Навык 20 year')),
                ('Skill21', models.TextField(verbose_name='Навык 21 year')),
                ('Skill22', models.TextField(verbose_name='Навык 22 year')),
                ('Skill23', models.TextField(verbose_name='Навык 23 year')),
            ],
            options={
                'verbose_name': 'Контент: Навыки',
                'verbose_name_plural': 'Контент: Навыки',
            },
        ),
        migrations.AlterField(
            model_name='geographypageinfo',
            name='Count1',
            field=models.IntegerField(verbose_name='Доля вакансий 1'),
        ),
        migrations.AlterField(
            model_name='geographypageinfo',
            name='Count2',
            field=models.IntegerField(verbose_name='Доля вакансий 2'),
        ),
        migrations.AlterField(
            model_name='geographypageinfo',
            name='Count3',
            field=models.IntegerField(verbose_name='Доля вакансийт 3'),
        ),
        migrations.AlterField(
            model_name='geographypageinfo',
            name='Count4',
            field=models.IntegerField(verbose_name='Доля вакансий 4'),
        ),
        migrations.AlterField(
            model_name='geographypageinfo',
            name='Count5',
            field=models.IntegerField(verbose_name='Доля вакансий 5'),
        ),
    ]
