# Generated by Django 4.1.5 on 2023-01-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skillspageinfo_alter_geographypageinfo_count1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_16',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_17',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_18',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_19',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_20',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_21',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_22',
        ),
        migrations.RemoveField(
            model_name='relevancepageinfo',
            name='SalaryByYears_23',
        ),
        migrations.AddField(
            model_name='relevancepageinfo',
            name='SalaryByYears_Table',
            field=models.FileField(blank=True, upload_to='app/static/files/', verbose_name='Таблица: Динамика уровня зарплат по годам(xcl)'),
        ),
    ]
