# Generated by Django 4.1.5 on 2023-01-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_geographypageinfo_count1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geographypageinfo',
            old_name='CountByYears_Graph',
            new_name='CountByCities_Graph',
        ),
        migrations.RenameField(
            model_name='geographypageinfo',
            old_name='CountByYears_Table',
            new_name='CountByCities_Table',
        ),
        migrations.RenameField(
            model_name='geographypageinfo',
            old_name='SalaryByYears_Graph',
            new_name='SalaryByCities_Graph',
        ),
        migrations.RenameField(
            model_name='geographypageinfo',
            old_name='SalaryByYears_Table',
            new_name='SalaryByCities_Table',
        ),
    ]
