# Generated by Django 4.1.5 on 2023-01-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_countbyyears_graph_geographypageinfo_countbycities_graph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill16',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill17',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill18',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill19',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill20',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill21',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill22',
        ),
        migrations.RemoveField(
            model_name='skillspageinfo',
            name='Skill23',
        ),
        migrations.AddField(
            model_name='skillspageinfo',
            name='Skills_Table',
            field=models.FileField(blank=True, upload_to='app/static/files/', verbose_name='Таблица: Навыки(xlsx)'),
        ),
    ]
